- .github/workflows/release.yml
> feat: use bot for commit

- src/mcp-nova-canvas-expert/pyproject.toml
- src/mcp-nova-canvas-expert/uv.lock
> feat: release nova canvas

- .github/workflows/release.yml
> fix: use bot

- .github/workflows/gh-pages.yml
- docs/index.md
- mkdocs.yml
- src/mcp-bedrock-kb-retrieval-expert/README.md
- src/mcp-nova-canvas-expert/README.md
> Canvas readme

- src/cost-analysis-mcp-server/README.md
Update README for cost analysis MCP server
> Add README for cost analysis mcp server

- README.md
- docs/servers/cdk-mcp-server.md
- src/bedrock-kb-retrieval-mcp-server/README.md
- src/cdk-mcp-server/README.md
- src/cost-analysis-mcp-server/README.md
- src/nova-canvas-mcp-server/README.md
Updated src/cdk-mcp-server/README.md:
- Added a structured Features section with detailed descriptions of Tools and Resources
- Added Prerequisites and Installation instructions
- Included Security Considerations section with guidance on CDK Nag usage
- Improved overall formatting and readability
> docs: update CDK MCP Server documentation and other minor fix

- src/cost-analysis-mcp-server/README.md
updated env vars in mcp server configuration
> Update env for mcp server configuration

- docs/servers/core-mcp-server.md
- mkdocs.yml
- src/core-mcp-server/README.md
- created docs/core-mcp-server.md
- added Core and CDK to mkdocs.yml
- updated Core installation guide (fixed typo, use uvx instead of uv tool install) in README.
> docs: add Core and CDK to mkdocs.yml and update Core readme

- src/core-mcp-server/README.md
> core: specify version of the server in mcp configuration

- README.md
- docs/index.md
- docs/servers/cdk-mcp-server.md
- docs/servers/nova-canvas-mcp-server.md
- mkdocs.yml
- src/bedrock-kb-retrieval-mcp-server/README.md
- src/cdk-mcp-server/README.md
- src/nova-canvas-mcp-server/README.md
> docs: service naming convention

- README.md
- src/bedrock-kb-retrieval-mcp-server/README.md
- src/cdk-mcp-server/README.md
- src/cost-analysis-mcp-server/README.md
- src/nova-canvas-mcp-server/README.md
Update README with updated python version requirement.
> Update README with updated python version

- src/core-mcp-server/awslabs/core_mcp_server/available_servers.py
- src/core-mcp-server/awslabs/core_mcp_server/static/PROMPT_UNDERSTANDING.md
*Description of changes:Added reference to awslabs.aws-documentation-mcp-server
> feat(core-mcp-server): add reference to aws-documentation-mcp-server

- README.md
- src/aws-documentation-mcp-server/README.md
> Update MCP documentation server package to use latest version

- src/cdk-mcp-server/awslabs/cdk_mcp_server/static/bedrock/knowledgebases/chunking.md
> docs: update chunking.md

- README.md
> fix: Correct typo in Example configuration for Amazon Q CLI MCP

- README.md
> docs(README): removes trailing comma

- src/cdk-mcp-server/README.md
- src/cdk-mcp-server/awslabs/cdk_mcp_server/core/tools.py
- src/cdk-mcp-server/awslabs/cdk_mcp_server/data/schema_generator.py
- src/cdk-mcp-server/uv.lock
- Improve error messages with clear dependency installation instructions 
- Add comprehensive next steps with CDK integration examples after schema generation 
- Update dependency detection with actionable guidance on how to resolve issues 
- Update README with detailed Developer Notes section for guidance 
- Simplify confusing output messages like Pydantic v2 OpenAPI warnings 
- Update mermaid diagram to show dependency installation flow
> feat(cdk-schema-generator): enhance Bedrock Agent Schema Generator UX

- .github/SUPPORT
- .github/pull_request_template.md
- .github/workflows/python.yml
- .github/workflows/stale.yml
- run ruff check and format in CI
- update PR template
- add stale workflow
> chore(github): update github config

- .github/workflows/bandit.yml
- .github/workflows/cfn_nag.yml
- .github/workflows/checkov.yml
- .github/workflows/codeql.yml
- .github/workflows/powershell.yml
- .github/workflows/pre-commit.yml
- .github/workflows/python.yml
- .github/workflows/semgrep.yml
- .github/workflows/stale.yml
- .github/workflows/trivy.yml
N/A
Add scanners to cover a wider array of languages and frameworks.
Adding scanners for the repository
* bandit
* cfn_nag
* checkov
* powershell
* semgrep
* trivy
Upon pushes or PRs into `main` scanners will run.
* [x ] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [ x] I have performed a self-review of this change
* [ x] Changes have been tested
* [ x] Changes are documented
<details>
<summary>Is this a breaking change? No</summary>
N/A
Checklist:
</details>
By submitting this pull request, I …
> feat: add required scanners

- README.md
This pull request includes a small update to the `README.md` file. The change modifies the description of the AWS MCP servers to better highlight their benefits.
Updated description in `README.md`:
* Changed the description from "A suite of specialized MCP servers that bring AWS best practices directly to your development workflow." to "A suite of specialized MCP servers that help you get the most out of AWS, wherever you use MCP."
<details>
Checklist:
</details>
By submitting this pull request, I confirm that …
> docs: add vision statement

- src/core-mcp-server/awslabs/core_mcp_server/static/PROMPT_UNDERSTANDING.md
Did you mean query?
I think it's a typo? Did you mean query?
N/A
* [X ] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [NA] Changes have been tested
* [ NA] Changes are documented
<details>
Checklist:
</details>
> Update PROMPT_UNDERSTANDING.md -> Updating typo of "query"? I think?

- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/NOTICE
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/pyproject.toml
* Updating the NOTICE
* Updating the license text within the pyproject.toml
* Excluding the `.venv` directory for bandit
> feat: cookiecutter classifiers

- scripts/release.py
> fix: code findings for release.py

- .github/workflows/pre-commit.yml
- .github/workflows/semgrep.yml
- src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/diagrams_tools.py
- src/cdk-mcp-server/awslabs/cdk_mcp_server/core/tools.py
- src/cdk-mcp-server/awslabs/cdk_mcp_server/static/__init__.py
- src/core-mcp-server/awslabs/core_mcp_server/static/__init__.py
- src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/static/__init__.py
- src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/static/patterns/__init__.py
N/A
Run semgrep without cli token or key to https://semgrep.dev/
Run action instead of through login to semgrep.
The user will have finding posted to the security findings.
<details>
<summary>Is this a breaking change? No</summary>
N/A
Checklist:
</details>
> fix: semgrep runs

- scripts/release.py
- src/aws-diagram-mcp-server/pyproject.toml
- src/aws-documentation-mcp-server/pyproject.toml
- src/bedrock-kb-retrieval-mcp-server/pyproject.toml
- src/cdk-mcp-server/pyproject.toml
- src/core-mcp-server/pyproject.toml
- src/cost-analysis-mcp-server/pyproject.toml
- src/lambda-mcp-server/pyproject.toml
- src/nova-canvas-mcp-server/pyproject.toml
N/A
Follow semantic versioning.
Instead of having the patch be the release build, use the build meta data https://semver.org/#spec-item-10
Downstream users will be able to rely on semantic versioning, while previously the patch was applied automatically.
Authors will control the patch now.
<details>
Checklist:
</details> …
> feat: semantic versioning build metadata

- CONTRIBUTING.md
- src/bedrock-kb-retrieval-mcp-server/README.md
**Issue number:** #140 
Fix documentation 
Update the documentation for the KB MCP server
<details>
Checklist:
</details>
> fix(doc): fix documentation

- README.md
- docs/index.md
- docs/servers/terraform-mcp-server.md
- mkdocs.yml
Adding Terraform MCP server to README and docs/server folder. 
<details>
Checklist:
</details>
> docs: adding tf server to readme + docs

- .github/pull_request_template.md
No hiding within the PR template.
> feat(template): unhide the details

- README.md
> fix: pypi reference for lambda

- src/aws-diagram-mcp-server/run_tests.sh
N/A
Missing check for mcp package.
Add a check for the mcp package in the test script.
Users that don't have mcp installed will install mcp in their test python environment.
Checklist:
> fix(tests): add check for missing mcp package

- samples/README.md
N/A
Pages build broken
https://github.com/awslabs/mcp/actions/runs/14527750932/job/40762331969#step:8:15
Reference GitHub, not relative path.
Checklist:
> fix: pages build broken

- src/git-repo-research-mcp-server/tests/test_graphql_github_search.py
- src/git-repo-research-mcp-server/tests/test_local_repository.py
- src/git-repo-research-mcp-server/tests/test_repository_utils.py
- src/git-repo-research-mcp-server/tests/test_url_repository.py
> feat: add test coverage; merge into Jon's fork

- src/git-repo-research-mcp-server/tests/test_github_search_edge_cases.py
- src/git-repo-research-mcp-server/tests/test_server.py
> add additional tests for coverage

- .github/workflows/scorecard-analysis.yml
N/A
Add the Open Source Security Foundation score card
Checklist:
> feat: ossf scorecard

- src/core-mcp-server/awslabs/core_mcp_server/static/PROMPT_UNDERSTANDING.md
Fixes
Adding Terraform MCP Server to the Core available tools and tools examples
Checklist:
> fix: adding terraform mcp server to core prompt understanding

- .github/workflows/scanners.yml
Fixes incorrect logic in detection of secrets
Fix detection of secrets.
Checklist:
> fix: detect-secrets logic should alert when there IS a secret

- src/aws-documentation-mcp-server/README.md
make the Q Developer CLI MCP config consistent to be consistent with the others
Fixes
Checklist:
> chore: fix aws-documentation-mcp-server readme

- .github/workflows/code-review-process.yml
- .github/workflows/code-review-request.yml
Preparation for an automated code review system.
This creates a pull request check and a repository dispatch to run.
Checklist:
> feat: code reviewer stub

- src/aws-diagram-mcp-server/README.md
Fixes
Added a quick example to the README.md for the aws diagram server
Users get an idea on how to make a diagram quickly.
Checklist:
> chore: update README.md for aws diagram mcp server

- DEVELOPER_GUIDE.md
- README.md
Add code coverage badge and information for contributors development requirements.
Checklist:
> feat(doc): display code coverage and document for development

- src/cost-analysis-mcp-server/README.md
- src/cost-analysis-mcp-server/uv.lock
Fixes
update README for cost server 
Checklist:
> chore: update README for cost server

- README.md
Fixes
update README for cost-analysis mcp server use case
Checklist:
> chore: update README for cost-analysis mcp server use case

- .github/workflows/merge-prevention.yml
Prevent unintentional merges
Checklist:
> feat: merge prevention by label

- README.md
Add documentation for the newly integrated Git Repo Research MCP Server including its features and configuration options.
Fixes
updated README.md
updated README.md
**RFC issue number**: n/a
Checklist:
> docs(readme): add Git Repo Research MCP Server documentation

- mkdocs.yml
Fixes
Typo in Terraform MCP Server markdown file name
Checklist:
> fix: nav terraform mcp server md typo

- .github/actions/build-and-push-container-image/action.yml
- .github/codecov.yml
- src/core-mcp-server/awslabs/core_mcp_server/__init__.py
> fix: correct path to public ecr

- README.md
Fix a minor typo issue in README.md. Correct 'includ' to 'include'.
Checklist:
> fix: minor typo issue in README.md

- .github/workflows/python.yml
> fix: cyclonedx to JSON format

- .github/workflows/claude.yml
Fixes #284 
Adopts code reviews by @awslabs-mcp
Runs only when the PR is labeled `code-review` into the default branch (`main`).
Only after runs (besides "self") complete with `success`, an environment approval from a @awslabs/mcp-admins  or @awslabs/mcp-maintainers team member (not self) can be run.
Checklist:
> feat: approval for code reviews

- .github/workflows/claude.yml
> fix: pull_request_target is the event type

- README.md
- src/amazon-mq-mcp-server/README.md
Fixes
Fix documentation error on amazon-mq-mcp-server and add it to the main README
N/A
* [x ] Changes are documented
N
N/A
Checklist:
> docs: Fix amazon-mq-mcp-server readme mcp

- .github/workflows/gh-pages.yml
- mkdocs.yml
> fix: mermaid2 plugin version and CDN location

- mkdocs.yml
> fix: privacy plugins for mkdocs

- src/amazon-mq-mcp-server/docker-healthcheck.sh
- src/amazon-sns-sqs-mcp-server/docker-healthcheck.sh
- src/aws-diagram-mcp-server/docker-healthcheck.sh
- src/aws-documentation-mcp-server/docker-healthcheck.sh
- src/aws-location-mcp-server/docker-healthcheck.sh
- src/bedrock-kb-retrieval-mcp-server/docker-healthcheck.sh
- src/cdk-mcp-server/docker-healthcheck.sh
- src/cfn-mcp-server/docker-healthcheck.sh
- src/core-mcp-server/docker-healthcheck.sh
- src/cost-analysis-mcp-server/docker-healthcheck.sh
- src/dynamodb-mcp-server/docker-healthcheck.sh
- src/lambda-mcp-server/docker-healthcheck.sh
- src/nova-canvas-mcp-server/docker-healthcheck.sh
- src/postgres-mcp-server/docker-healthcheck.sh
- src/terraform-mcp-server/docker-healthcheck.sh
> fix: docker healthchecks

- .github/workflows/claude.yml
> fix: allow a code review when labeled hold-merging

- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/Dockerfile
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/docker-healthcheck.sh
> feat: add container to python cookiecutter

- .github/workflows/claude.yml
> fix: increase claude code timeout

- src/postgres-mcp-server/awslabs/postgres_mcp_server/mutable_sql_detector.py
- src/postgres-mcp-server/awslabs/postgres_mcp_server/server.py
- src/postgres-mcp-server/tests/conftest.py
- src/postgres-mcp-server/tests/test_server.py
Fixes
Address issue raised by private ticket [removed]
1. Improve risky query pattern detection
2. Always execute under readonly transaction if the setting of readonly is true as catch all safety net.
3. Improve test cases
No change
* [x ] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [ x] I have performed a self-review of this change
* [ x] Changes have been tested
* [ x] Changes are documented
Is this a breaking change? (Y/N) No
N/A
Checklist:
* [ x] Migration process documented
* [ x] Implement warnings (if it can live side by side)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> fix(Postgres): fix issue and beef up overall security test cases

- README.md
- docs/index.md
- src/memcached-mcp-server/ELASTICACHECONNECT.md
- src/valkey-mcp-server/ELASTICACHECONNECT.md
> chore(doc): improve service naming consistency and fix links

- src/cfn-mcp-server/awslabs/cfn_mcp_server/aws_client.py
- src/cfn-mcp-server/awslabs/cfn_mcp_server/server.py
- src/cfn-mcp-server/pyproject.toml
- src/cfn-mcp-server/uv.lock
Adding a user agent to the CFN MCP Server
Adding a user agent to the CFN MCP Server
No change
* [y] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [y] I have performed a self-review of this change
* [y] Changes have been tested
* [y] Changes are documented
Checklist:
> chore: Adding user agent to cfn mcp server

- README.md
Fixes
This PR adds the Finch MCP Server to the main README.md file, making it visible and accessible to users browsing the repository.
Checklist:
> docs: add finch info to main readme.md

- src/aws-support-mcp-server/pyproject.toml
- src/aws-support-mcp-server/uv.lock
> fix: update pyproject.toml

- .gitignore
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/Dockerfile
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/__init__.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-') | replace('-', '_')}}_mcp_server/__init__.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/awslabs/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-') | replace('-', '_')}}_mcp_server/server.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/docker-healthcheck.sh
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/pyproject.toml
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_init.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_main.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/test_server.py
> fix: cookiecutter license and updates

- .github/workflows/release.yml
- .github/workflows/typescript.yml
> fix: permissions removed at top-level

- src/amazon-mq-mcp-server/README.md
- src/amazon-sns-sqs-mcp-server/README.md
…ervers
Fixes
Update documentation on AMQ and SNS-SQS MCP
AMQ and SNS-SQS MCP
No change
N
N
Checklist:
> docs: suggest using IAM role instead of user on AMQ and SNS-SQS MCP

- src/eks-mcp-server/awslabs/eks_mcp_server/eks_kb_handler.py
- src/lambda-tool-mcp-server/examples/README.md
Some typos are present in documentation
Typo fixes
Checklist:
> docs: fix typos

- .github/workflows/cfn_nag.yml
Improves #546
pins CFN Nag tool
Checklist:
> fix: update to commit hash

- README.md
> docs: tweak some service names

- src/elasticache-mcp-server/README.md
- src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/cw/get_metric_statistics.py
- src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/create.py
- src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/delete.py
- src/elasticache-mcp-server/awslabs/elasticache_mcp_server/tools/serverless/modify.py
- src/elasticache-mcp-server/tests/tools/cw/test_get_metric_statistics.py
- src/elasticache-mcp-server/uv.lock
- src/memcached-mcp-server/uv.lock
- src/valkey-mcp-server/uv.lock
Fixes
Minor fixes in ElastiCache mcp server
Minor fixes in ElastiCache mcp server
No changes to user experience
Checklist:
> fix: minor fixes in elasticache mcp server

- CONTRIBUTING.md
Adds a special consideration for server categorization in the root readme
Checklist:
> docs(CONTRIBUTING): add a section on server categorization

- docs/servers/aurora-dsql-mcp-server.md
Fixes
remove indentation in aurora-dsql-mcp-server.md
```bash
% git diff
diff --git a/docs/servers/aurora-dsql-mcp-server.md b/docs/servers/aurora-dsql-mcp-server.md
index 97753ad..62ea7d9 100644
--- a/docs/servers/aurora-dsql-mcp-server.md
+++ b/docs/servers/aurora-dsql-mcp-server.md
@@ -1,5 +1,5 @@
-    ---
-    title: Amazon Aurora DSQL MCP Server
-    ---
+---
+title: Amazon Aurora DSQL MCP Server
+---
-    {% include "../../src/aurora-dsql-mcp-server/README.md" %}
+{% include "../../src/aurora-dsql-mcp-server/README.md" %}
```
Currently (2025/06/18), all documentation in [aurora-dsql-mcp-server](https://awslabs.github.io/mcp/servers/aurora-dsql-mcp-server/ …
> docs: remove unnecessary indentation in aurora-dsql-mcp-server.md

- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/__init__.py
- python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/tests/conftest.py
> feat: add conftest to cookiecutters

- .github/CODEOWNERS
> refactor: add missing MCP servers and alphabetized

- mkdocs.yml
Fixes #659 
Add AWS Bedrock Data Automation to the menu
Checklist:
> docs: add aws bedrock data automation to documenation

- src/aws-support-mcp-server/awslabs/aws_support_mcp_server/client.py
Add User Agent to AWS Support MCP Server
Fixes
I added a user agent to AWS Support MCP.
Users can track their usage of the AWS Support MCP in their Cloudtrail.
N
630
Checklist:
> fix: Update AWS Support MCP with User Agent

- src/aws-dataprocessing-mcp-server/README.md
- src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/handlers/emr/emr_ec2_cluster_handler.py
- src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/handlers/emr/emr_ec2_instance_handler.py
- src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/handlers/emr/emr_ec2_steps_handler.py
- src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/models/emr_models.py
- src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/server.py
- src/aws-dataprocessing-mcp-server/tests/handlers/emr/__init__.py
- src/aws-dataprocessing-mcp-server/tests/handlers/emr/test_emr_ec2_cluster_handler.py
- src/aws-dataprocessing-mcp-server/tests/handlers/emr/test_emr_ec2_instance_handler.py
- src/aws-dataprocessing-mcp-server/tests/handlers/emr/test_emr_ec2_steps_handler.py
- src/aws-dataprocessing-mcp-server/tests/models/test_emr_models.py
- src/aws-dataprocessing-mcp-server/tests/test_server.py
The AWS Data Processing MCP Server now includes comprehensive support for Amazon EMR EC2 operations through three specialized handlers:
- __EMR EC2 Cluster Handler__: Manages the complete lifecycle of EMR clusters, including creation, configuration, modification, and termination. It also supports security configuration management.
- __EMR EC2 Instance Handler__: Provides capabilities for managing instance fleets and instance groups within EMR clusters, including adding new instances, modifying existing ones, and listing instance details.
- __EMR EC2 Steps Handler__: Enables management of processing steps on EMR clusters, including adding new steps, canceling running steps, describing step details, and listing steps with various filters.
> Before this change:
Users had no options for …
> feat(dataprocessing-mcp-server): Add EMR-EC2 Cluster, Steps, Instance management tools

- docs/servers/aws-dataprocessing-mcp-server.md
- mkdocs.yml
Fixes
Add a entry in mkdocs.yml for aws-dataprocessing-mcp-server
> Before
the deployment for dataprocessing-mcp has failed - https://github.com/awslabs/mcp/actions/runs/16130181219/job/45515926800 
> After
it is expected to pass
https://github.com/awslabs/mcp/issues/614
Checklist:
> chore(dataprocessing-mcp-server): Add Doc Update in mkdocs.yml

- README.md
Minor Fixes on AWS MCP Server for Data Processing (Ref)
Update README refs for `aws-dataprocessing-mcp-server`.
Checklist:
> fix(aws-dataprocessing-mcp-server): Update README typo for dataprocessing MCP server

- .github/workflows/check-gh-pages-builds.yml
- docusaurus/docusaurus.config.ts
> chore: check gh pages builds

- src/aws-api-mcp-server/CHANGELOG.md
Added first entry in the CHANGELOG for the initial release.
Checklist:
> chore(aws-api-mcp-server): Add CHANGELOG entry for the initial release

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/support_awslabs_mcp_servers.yml
This pull request includes the newly released AWS API MCP as part of the project templates.
No changes
> chore: add AWS API MCP server as part of the issue templates

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/__init__.py
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/dense_retriever.py
- src/aws-api-mcp-server/tests/kb/test_dense_retriever.py
- src/aws-api-mcp-server/tests/kb/test_knowledge_base.py
- src/aws-api-mcp-server/tests/test_server.py
SentenceTransformers are prone to high latency, which can be incurred at start-time of the server or at call time for the `suggest_aws_commands` tool. Because this tool is technically not invoked most of the time as foundational models know already the most popular APIs, we can attempt to load sentence transformers and the initial download in background to mitigate the perceived latency of the tool.
Fixes
With this change the sentence transformer and the model for embeddings are downloaded at server time in background - by the time the user interacts with the `suggest_aws_commands` tool, the model should be downloaded and the sentence transformer library should be imported, but it all depends on how soon the host leverages the suggest command.
If your change doesn't seem to apply, please …
> chore(aws-api-mcp-server): Load the sentence transformers in background

- src/aws-pricing-mcp-server/awslabs/aws_pricing_mcp_server/__init__.py
- src/aws-pricing-mcp-server/awslabs/aws_pricing_mcp_server/server.py
Fixes
* remove emojis from get_pricing tool documentation for better compatibility with LLM processing and technical contexts
* document savings plans support in get_price_list_urls tool
Before, documentation contained emojis (✅, ⚠️) which could cause rendering issues and get_price_list_urls description lacked explicit mention of Savings Plans support.
After, improved compatibility for technical contexts and LLM processing and explicit documentation of Savings Plans support in get_price_list_urls tool
Checklist: …
> docs(aws-pricing-mcp-server): remove emojis from get_pricing tool and document savings plans support in get_price_list_urls tool

- src/aws-api-mcp-server/pyproject.toml
Release failed and fixed with #878 
Revert the bumped never-released version.
Checklist:
> chore: revert for release bump

- src/aws-diagram-mcp-server/Dockerfile
- src/s3-tables-mcp-server/Dockerfile
- src/terraform-mcp-server/Dockerfile
> fix: convert sam/build-python to python:alpine

- src/aws-knowledge-mcp-server/README.md
Fixes
Added production usage text to README
Checklist:
> docs: Add production usage message

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/s3-tables-mcp-server/awslabs/s3_tables_mcp_server/__init__.py
- src/s3-tables-mcp-server/pyproject.toml
Triggered Release v2 Branch (manual) by @scottschreckengaust for @scottschreckengaust
* s3-tables-mcp-server
> chore: release/2025.07.20250724233019

- src/aws-pricing-mcp-server/pyproject.toml
Triggered Release v2 Branch (manual) by @scottschreckengaust for @scottschreckengaust
* aws-pricing-mcp-server
> chore: release/2025.07.20250725184343

- src/s3-tables-mcp-server/awslabs/s3_tables_mcp_server/__init__.py
- src/s3-tables-mcp-server/pyproject.toml
Triggered Release v2 Branch (manual) by @okhomin for @okhomin
* s3-tables-mcp-server
> chore: release/2025.07.20250725211158

- src/eks-mcp-server/README.md
Fixes
https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line-mcp-configuration.html link is broken
Is this a breaking change? (Y/N) N 
Checklist:
> fix: update README.md

- .github/workflows/release-merge-tag.yml
- .github/workflows/release.py
- .github/workflows/release.yml
Fixes #966 
There may be times that packages should be skipped.
Place a `DO_NOT_RELEASE` file in the package directory (`/src/<PACKAGE>/DO_NOT_RELEASE`) for the release to skip the package during the process.
> feat: release skipping and bump fixing

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/aws-diagram-mcp-server/awslabs/aws_diagram_mcp_server/__init__.py
- src/aws-diagram-mcp-server/pyproject.toml
- src/aws-pricing-mcp-server/awslabs/aws_pricing_mcp_server/__init__.py
- src/aws-pricing-mcp-server/pyproject.toml
- src/mcp-lambda-handler/awslabs/mcp_lambda_handler/__init__.py
- src/mcp-lambda-handler/pyproject.toml
- src/s3-tables-mcp-server/awslabs/s3_tables_mcp_server/__init__.py
- src/s3-tables-mcp-server/pyproject.toml
Triggered Release Branch (initiated) by @okhomin for @okhomin
* aws-diagram-mcp-server
* aws-pricing-mcp-server
* mcp-lambda-handler
* s3-tables-mcp-server
> chore: release/2025.07.20250731231632

- src/postgres-mcp-server/README.md
> docs: fixing readme

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/cloudwatch-appsignals-mcp-server/awslabs/cloudwatch_appsignals_mcp_server/__init__.py
- src/cloudwatch-appsignals-mcp-server/pyproject.toml
- src/core-mcp-server/awslabs/core_mcp_server/__init__.py
- src/core-mcp-server/pyproject.toml
- src/cost-explorer-mcp-server/awslabs/cost_explorer_mcp_server/__init__.py
- src/cost-explorer-mcp-server/pyproject.toml
- src/finch-mcp-server/awslabs/finch_mcp_server/__init__.py
- src/finch-mcp-server/pyproject.toml
- src/postgres-mcp-server/awslabs/postgres_mcp_server/__init__.py
- src/postgres-mcp-server/pyproject.toml
Triggered Release Branch (initiated) by @alexa-perlov for @alexa-perlov
* cloudwatch-appsignals-mcp-server
* core-mcp-server
* cost-explorer-mcp-server
* finch-mcp-server
* postgres-mcp-server
> chore: release/2025.08.20250804210840

- src/aws-api-mcp-server/CHANGELOG.md
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/service.py
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/__init__.py
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/dense_retriever.py
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/server.py
- src/aws-api-mcp-server/tests/aws/test_service.py
- src/aws-api-mcp-server/tests/test_server.py
- src/aws-api-mcp-server/uv.lock
Fixes
Improve logs by:
- logging the input when tools are invoked
- adding operation timer for customizations just like we have for boto3 operations
- logging embedding model startup for easier debugging
Checklist:
> fix(aws-api-mcp-server): Improve logging

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/__init__.py
- src/dynamodb-mcp-server/pyproject.toml
Triggered Release Branch (initiated) by @scottschreckengaust for @scottschreckengaust
* dynamodb-mcp-server
> chore: release/2025.08.20250806001353

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/aws-pricing-mcp-server/awslabs/aws_pricing_mcp_server/__init__.py
- src/aws-pricing-mcp-server/pyproject.toml
- src/eks-mcp-server/awslabs/eks_mcp_server/__init__.py
- src/eks-mcp-server/pyproject.toml
Triggered Release Branch (initiated) by @rshevchuk-git for @rshevchuk-git
* aws-pricing-mcp-server
* eks-mcp-server
> chore: release/2025.08.20250807085838

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
Triggered Release Branch (initiated) by @arnewouters for @arnewouters
> chore: release/2025.08.20250811131021

- .github/workflows/check-license-header.json
> chore(build): update license check

- .github/workflows/check-license-header.yml
> chore(build): update strict mode

- src/ccapi-mcp-server/Dockerfile
> fix(ccapi): pin requirements

- src/aws-api-mcp-server/CHANGELOG.md
- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/parser/interpretation.py
- src/aws-api-mcp-server/uv.lock
Fixes
Add telemetry string in user agent for the consent mechanism
Checklist:
> feat(aws-api-mcp-server): telemetry for consent mechanism

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/aws-api-mcp-server/uv.lock
- src/aws-healthomics-mcp-server/awslabs/aws_healthomics_mcp_server/__init__.py
- src/aws-healthomics-mcp-server/pyproject.toml
- src/aws-healthomics-mcp-server/uv.lock
- src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/__init__.py
- src/aws-iot-sitewise-mcp-server/pyproject.toml
- src/aws-iot-sitewise-mcp-server/uv.lock
- src/aws-msk-mcp-server/awslabs/aws_msk_mcp_server/__init__.py
- src/aws-msk-mcp-server/pyproject.toml
- src/aws-msk-mcp-server/uv.lock
- src/ecs-mcp-server/awslabs/ecs_mcp_server/__init__.py
- src/ecs-mcp-server/pyproject.toml
- src/ecs-mcp-server/uv.lock
- src/redshift-mcp-server/awslabs/redshift_mcp_server/__init__.py
- src/redshift-mcp-server/pyproject.toml
- src/redshift-mcp-server/uv.lock
Triggered Release Branch (initiated) by @arnewouters for @arnewouters
* aws-healthomics-mcp-server
* aws-iot-sitewise-mcp-server
* aws-msk-mcp-server
* ecs-mcp-server
* redshift-mcp-server
> chore: release/2025.09.20250922121130

- src/ecs-mcp-server/awslabs/ecs_mcp_server/__init__.py
- src/ecs-mcp-server/pyproject.toml
- src/ecs-mcp-server/uv.lock
Triggered Release Branch (initiated) by @scottschreckengaust for @scottschreckengaust
* ecs-mcp-server
> chore: release/2025.09.20250922202404

- src/aws-iot-sitewise-mcp-server/DEVELOPMENT.md
> fix: fix pip install

- src/aws-api-mcp-server/awslabs/aws_api_mcp_server/__init__.py
- src/aws-api-mcp-server/pyproject.toml
- src/aws-api-mcp-server/uv.lock
- src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/__init__.py
- src/aws-documentation-mcp-server/pyproject.toml
- src/aws-documentation-mcp-server/uv.lock
- src/aws-healthomics-mcp-server/awslabs/aws_healthomics_mcp_server/__init__.py
- src/aws-healthomics-mcp-server/pyproject.toml
- src/aws-healthomics-mcp-server/uv.lock
- src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/__init__.py
- src/aws-iot-sitewise-mcp-server/pyproject.toml
- src/aws-iot-sitewise-mcp-server/uv.lock
- src/cloudtrail-mcp-server/awslabs/cloudtrail_mcp_server/__init__.py
- src/cloudtrail-mcp-server/pyproject.toml
- src/cloudtrail-mcp-server/uv.lock
- src/ecs-mcp-server/awslabs/ecs_mcp_server/__init__.py
- src/ecs-mcp-server/pyproject.toml
- src/ecs-mcp-server/uv.lock
Triggered Release Branch (initiated) by @matthewgoodman13 for @matthewgoodman13
* aws-documentation-mcp-server
* aws-healthomics-mcp-server
* aws-iot-sitewise-mcp-server
* cloudtrail-mcp-server
* ecs-mcp-server
> chore: release/2025.09.20250929221000

- src/ecs-mcp-server/awslabs/ecs_mcp_server/modules/aws_knowledge_proxy.py
- src/ecs-mcp-server/tests/unit/modules/test_aws_knowledge_proxy.py
- Adds prompts/support for ECS Managed Instances
- Customers can ask questions about ECS Managed Instances, and the knowledge tools will return relevant info
- UTs pass
- Integ tests pass
- Own framework testing
* [Y] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [Y] I have performed a self-review of this change
* [Y] Changes have been tested
* [Y] Changes are documented
Checklist:
* [NA] Migration process documented
* [NA] Implement warnings (if it can live side by side)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …
> feat(ecs-mcp-server): add support for managed instances

- src/aws-api-mcp-server/CHANGELOG.md
- src/aws-api-mcp-server/README.md
- src/aws-api-mcp-server/pyproject.toml
- src/aws-api-mcp-server/uv.lock
> chore(aws-api-mcp-server): prepare for release 1.0.0

- src/aws-iot-sitewise-mcp-server/Dockerfile
- src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/prompts/data_exploration.py
- src/aws-iot-sitewise-mcp-server/awslabs/aws_iot_sitewise_mcp_server/prompts/data_ingestion.py
Fixes
Update the container base python image for iot-sitewise
Checklist:
> fix: update iot sitewise container image
