awslabs/mcp

README.md, docs/index.md, docs/servers/aws-documentation-mcp-server.md
- Introduced a new section in README.md for the AWS Documentation MCP Server, highlighting its features and providing links to further documentation.
- Updated index.md to include an overview of the AWS Documentation MCP Server and its capabilities.
- Created a new documentation file for the AWS Documentation MCP Server, linking to its README for detailed information.
=> docs: add AWS Documentation MCP Server details to README and index

README.md
https://github.com/awslabs/mcp/issues/68
Update README to clarify AWS MCP Servers as an implementation of Model Context Protocol for AWS.
=> docs: add definition of MCP server to README

.github/workflows/python.yml
*Description of changes:* upload bandit scan report even when the step fails
=> chore(bandit): upload report when step fails

python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/pyproject.toml
N/A
Add bandit exclusions in the pyproject.toml file.
=> fix: add bandit exclusions for python cookiecutter

CONTRIBUTING.md
- Add instructions for configuring local MCP server settings
- Include JSON configuration example
- Improve documentation clarity for developer testing
Updates CONTRIBUTING.md with instructions for testing against a local MCP server development environment. This addition helps developers verify their tools and instructions with the MCP Client locally before deployment.
- Added new section "Testing with a Local Development MCP Server"
- Included JSON configuration example for server settings
- Improved documentation clarity and formatting
=> docs: update CONTRIBUTING.md with local MCP server testing guide

src/core-mcp-server/awslabs/core_mcp_server/static/PROMPT_UNDERSTANDING.md, src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/report_generator.py, src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py, src/cost-analysis-mcp-server/uv.lock
**Issue number:** https://github.com/awslabs/mcp/issues/94
Fix cost analysis server integration with Q CLI
Integration with Q CLI failing because tool name is too long. Changed the tool names.
<details>
Checklist:
</details>
=> Fix cost analysis server integration with Q CLI

python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/LICENSE, python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/NOTICE, python/{{cookiecutter.project_domain | lower | replace(' ', '-') | replace('_', '-')}}-mcp-server/pyproject.toml
Add urls, LICENSE and NOTICE to the cookie cutter
=> feat: cookiecutters license urls

src/aws-diagram-mcp-server/pyproject.toml
- N/A
- Align with other project's toml file to ignore these directories
- Bandit will ignore the ["venv","tests"] directories for the diagram mcp server
<details>
Checklist:
</details>
=> fix(toml): add ignore

src/aws-diagram-mcp-server/pyproject.toml, src/aws-diagram-mcp-server/uv.lock
Fixed missing namespace in package.
=> fix: name of diagram package

docs/servers/aws-diagram-mcp-server.md
**Issue number:** N/A
Fix the incorrect title in the AWS Diagram MCP Server documentation.
The current title is "AWS Documentation MCP Server", but it should be "AWS Diagram MCP Server".
Updated `docs/servers/aws-diagram-mcp-server.md` and tested.
<details>
Checklist:
</details>
=> docs: fix incorrect title in AWS Diagram MCP Server documentation

docs/index.md
The title and link before the "Installation and Setup" section on the MCP documentation page (https://awslabs.github.io/mcp/) were incorrect. I updated both to properly reference the AWS Diagram MCP Server documentation.
<details>
Checklist:
</details>
=> fix(docs): fix title and link for AWS Diagram MCP server docs

src/lambda-mcp-server/examples/sample_functions/template.yml
N/A
Suppress CFN Nag warnings
The warning to run a lambda with reserved concurrency and within a VPC is not required for this example.
The `cfn_nag` will not throw warnings locally due to the added suppression.
<details>
<summary>Is this a breaking change? No</summary>
N/A
Checklist:
</details>
=> fix(cfn_nag): suppress W89 and W92

docs/index.md
**Issue number:** N/A
Fix the incorrect url in the AWS Terraform MCP Server documentation.
From `terrafrom` to `terraform`.
Updated `docs/index.md` and tested.
Checklist:
=> docs: fix incorrect url in AWS Terraform MCP Server documentation

src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/report_generator.py, src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py, src/cost-analysis-mcp-server/tests/test_report_generator.py
https://github.com/awslabs/mcp/issues/148
Fix typeError by:
Adding proper type checking in _format_value function
Adding safe string conversion for keys
Adding error handling with try-catch block
Checklist:
=> fix: type errors in generate_cost_report tool

samples/mcp-integration-with-kb/README.md
**Issue number:** #174
> Resolves broken image in docs
Is this a breaking change? No
Checklist:
=> fix(docs): Resolves #174 - broken image in docs

samples/mcp-integration-with-kb/README.md, src/aws-documentation-mcp-server/README.md
**Issue number:** #174 
- Fixed broken basic-usage.gif in MkDocs site
Checklist:
=> fix: doc image

.github/workflows/release.yml
**Issue number:* #190 
Update the release workflow to prevent running on forks
See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
None
Checklist:
=> chore(release): update release workflow

.github/pull_request_template.md
Update the PR template -> update default keyword to automatically link an issue to a pr
See documentation: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
Updating the keyword to automatically linking an issue to a pr
Users won't have to manually close issues if the issue is correctly attached
Checklist:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> chore(pr): update pr template keyword

src/terraform-mcp-server/tests/test_search_user_provided_module.py, src/terraform-mcp-server/uv.lock
Fixes
Adding additional test coverage for the user provided module tool in the Terraform MCP server. 
Checklist:
=> test(terraform mcp server): adding test coverage for user provided module tool

.github/workflows/python.yml
Fixes #125 
The `set-output` command is deprecated and will be disabled soon. 
So, I've updated to use `$GITHUB_OUTPUT` instead.
Nothing changes
`N`
closes #125
Checklist:
=> fix: use GITHUB_OUTPUT instead

src/cost-analysis-mcp-server/README.md
building docker image in cost-analysis mcp server should be called awslabs/cost-analysis-mcp-server and not awslabs/bedrock-kb-retrieval-mcp-server
innstroduced in https://github.com/awslabs/mcp/pull/204
Fixes
Checklist:
=> docs: fix typo in cost-analysis-mcp-server readme

src/aws-diagram-mcp-server/README.md
Code snippet in src/aws-diagram-mcp-server/README.md was incorrectly refering the Dynamodb from diagrams.aws.package resulting in error -> ImportError: cannot import name 'DynamoDB' from 'diagrams.aws.database'
The diagrams package(https://diagrams.mingrammer.com/docs/nodes/aws) refers DynamoDB component  as diagrams.aws.database.dynamodb, DDB (alias) and not from diagrams.aws.database.DynamoDB.
changed code in documentation to reflect that.
Fixes
Checklist:
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> chore(doc): Update README.md - src/aws-diagram-mcp-server/README.md

README.md
Fixes #196 
> Added a note in the readme.md regarding usage of the `@latest` suffix on uvx based tools and possible performance degradation versus not using it.
> Users should be able to understand the implications of leaving the `@latest` or removing it altogether and what to do to always retrieve the latest mcp versions.
**RFC issue number**: 196
Checklist:
=> docs: add note regarding the performance hit of using the latest suffix in uvx based tools

.github/codecov.yml
Having zero code coverage occasionally fails the build even when there are no code lines to cover, so reducing the zero to a 0.1 % lowering
Fixes
Checklist:
=> fear: almost zero change in code coverage

README.md
there was a syntax error in mcp.json
If copy pasted as is, it would give an error that is tough to diagnose. By removing this comma, it will actually work as pasted.
Fixes
Checklist:
=> fix: JSON syntax

.devcontainer/devcontainer.json, .github/CODEOWNERS
Fixes #283
Add a default dev container
Checklist:
=> feat: default devcontainer

.github/actions/build-and-push-container-image/action.yml, src/lambda-mcp-server/awslabs/lambda_mcp_server/__init__.py, src/postgres-mcp-server/awslabs/postgres_mcp_server/__init__.py
Fixes when multiple docker image digests are uploaded as artifacts:
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
Checklist:
=> fix: release multiple digests

docs/servers/aws-location-mcp-server.md
Fixes
Fixed document path
Fixed document path
User will be able to refer to the correct document.
N
Checklist:
=> fix: fix the reference path for AWS Location MCP Server

src/cfn-mcp-server/README.md
The wrong package was in the installation instructions and there were some typos in the json formatting. This makes the installation reference better for copy/paste and addresses the package issue
Resolves https://github.com/awslabs/mcp/issues/340
> Fixed JSON format in README installation instructions
> Fixed package in mcp configuration in README
> Before - installation would fail - see https://github.com/awslabs/mcp/issues/340
> After - copy pasting the configuration should work
* [y] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [y] I have performed a self-review of this change
* [y] Changes have been tested
* [y] Changes are documented
Is this a breaking …
=> fix: Fixed the installation instructions in the CloudFormation MCP server

README.md
1. Remove the trailing comma after "FASTMCP_LOG_LEVEL": "ERROR"
2. Add the missing closing brace after the valkey-mcp-server section
3. Add a comma after the memcached-mcp-server closing brace
Fixes
Checklist:
=> fix(doc): syntax errors in mcp.json example

src/amazon-kendra-index-mcp-server/README.md
Updated ReadMe installation instructions to use remote server address for mcp server config
Fixes
Checklist:
=> chore(doc): Update README.md ofr Kendra Index MCP Server

src/dynamodb-mcp-server/README.md, src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/common.py, src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py, src/dynamodb-mcp-server/tests/test_dynamodb_server.py, src/dynamodb-mcp-server/tests/test_readonly_delete_table.py
1. Support read-only mode in dynamodb mcp
2. Support list import API
1. User can set DDB-MCP-READONLY in MCP.json to disable mutation API
2. User can now list import from last 90 days.
3. 
No
Checklist:
=> fix: support read-only mode for dynamodb mcp

README.md
Fixes
This PR fixes a JSON syntax error in the README.md file by adding a missing comma between the memcached-mcp-server and git-repo-research-mcp-server blocks in the configuration example.
Similar to the fix in PR #363.
User copies mcp.json to local and error occurs on loading q cli 
* [x ] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [x ] Changes have been tested
* [x ] Changes are documented
Is this a breaking change? (Y/N) n
Checklist:
=> fix(doc): JSON syntax errors in mcp.json example

src/amazon-mq-mcp-server/awslabs/amazon_mq_mcp_server/aws_service_mcp_generator.py, src/amazon-mq-mcp-server/tests/test_aws_service_mcp_generator.py, src/amazon-sns-sqs-mcp-server/awslabs/amazon_sns_sqs_mcp_server/generator.py, src/amazon-sns-sqs-mcp-server/tests/test_generator.py
Fixes
```
- Q CLI was giving us this issue:
Amazon Q is having trouble responding right now:
0: unhandled error (ValidationException)
1: service error
2: unhandled error (ValidationException)
3: Error { code: "ValidationException", message: "Improperly formed request.", aws_request_id: "3ea24471-777f-4114-8adc-f965c7ac75e6" }
Location:
crates/chat-cli/src/cli/chat/mod.rs:1008
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
>
```
After a dive deep, we were able to figure out its because of the signature of the function
It does not like signatures that look like this:
```
Generated signature for operation 'confirm_subscription':
(Token: str, TopicArn: str, AuthenticateOnUnsubscribe: …
```
=> fix: Fix Q related Issues

src/ecs-mcp-server/awslabs/ecs_mcp_server/templates/ecs_infrastructure.json
Fixes the circular dependency in the CloudFormation template between the ALBAccessLogsBucket and ALBAccessLogsBucketPolicy resources.
Looking at the template, the issue is that:
1. The ALBAccessLogsBucket resource (S3 bucket for ALB access logs) has a LoggingConfiguration property that references
itself. It's trying to log its own access logs to itself, which creates a circular reference.
2. The ALBAccessLogsBucketPolicy resource depends on the bucket, but the bucket also depends on the policy being in place
for its logging configuration.
This creates a "chicken and egg" problem where:
• The bucket needs the policy to be created first
• The policy needs the bucket to be created first
To fix this, we  remove the self-referential logging configuration from the S3 bucket
> Please provide a …
=> fix(ecs-mcp-server): fix circular dependency in ecs infrastructure template

src/eks-mcp-server/README.md
Fixes
1. Managing resources through CloudFormation requires many more permissions than what is in the recommended write operations policy. The user needs permissions for all of the resources in the template. The permissions were only allowing the user to initiate stack creation, but deployment would fail for resources in the stack. 
Updating the README to suggest using EKS full access (`eks:*`) and managed policies for the rest of the services in the cfn template.
2. `"aws:RequestTag/CreatedBy": "EksMcpServer"` also only allows CreateStack (it should be `ResourceTag`) - that condition gets removed with this change.
3. Highlighting that k8s APIs would only work when the user's principal actually created the cluster or has an EKS access entry in place. 
1. The generate and deploy workflow …
=> fix: (eks-mcp-server) update README section for write permissions

src/lambda-tool-mcp-server/awslabs/lambda_tool_mcp_server/server.py
Fixes
This Pull Request addresses an issue where `awslabs.lambda-tool-mcp-server` fails to discover and register Lambda functions as MCP tools when run via `uvx awslabs.lambda-tool-mcp-server@latest` (e.g., in environments like Cursor). The core change involves reordering function calls in the `main()` function of `servers/lambda-tool-mcp-server/awslabs/lambda_tool_mcp_server/server.py` to ensure Lambda functions are registered before the MCP server starts its blocking operation.
Specifically, the `register_lambda_functions()` call is moved to execute before `mcp.run()`.
**Before this change:**
When running `awslabs.lambda-tool-mcp-server` via `uvx awslabs.lambda-tool-mcp-server@latest` (e.g., in Cursor):
The server logs indicate successful startup and credential loading, but then report …
=> fix: Lambda functions not registering in MCP Server

src/cloudwatch-logs-mcp-server/CHANGELOG.md, src/cloudwatch-logs-mcp-server/README.md, src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/__init__.py, src/cloudwatch-logs-mcp-server/awslabs/cloudwatch_logs_mcp_server/server.py, src/cloudwatch-logs-mcp-server/tests/test_server.py, src/cloudwatch-logs-mcp-server/uv.lock
Fixes
* Fix user agent and add contributions link to readme
* Users can find requests from this MCP server in cloudtrail using UserAgent
**RFC issue number**: #430 
Checklist:
=> fix(logs): fix useragent setting and add contributions link

src/stepfunctions-tool-mcp-server/tests/test_server.py
Fixes #500 
During the release, versions are bumped only for the `pyproject.toml` files.
Disabled a test checking for equality on the `__version__`.
Checklist:
=> fix: remove test for equality of __version__

src/aws-serverless-mcp-server/README.md, src/aws-serverless-mcp-server/awslabs/aws_serverless_mcp_server/tools/sam/sam_build.py, src/aws-serverless-mcp-server/tests/test_sam_build.py
Ensure that builds for sam applications are in parallel.
Speed up in user experience for parallel builds whenever there are multiple build-able resources in the SAM template.
Checklist:
=> feat: sam_build_tool now runs in parallel by default

src/cloudwatch-logs-mcp-server/README.md
- Fix the training comma in in the `awslabs.cloudwatch-logs-mcp-server` example under `Installation`. The JSON in the example is currently no valid
- Before this change it was not possible to copy the example and have it working without any edits
Checklist:
=> fix: invalid JSON for cloudwatch-logs-mcp-server example

src/dynamodb-mcp-server/awslabs/dynamodb_mcp_server/server.py
This documentation improvement helps agents understand how to properly format attribute values when interacting with the DynamoDB MCP server.
- Add comprehensive explanation of DynamoDB attribute value formats with examples
- Clarify parameter descriptions to explicitly reference required format
- Update version from 0.1.1 to 0.1.2
None
Checklist:
fixes #564
=> fix(dynamodb-mcp-server): improve documentation for DynamoDB attribute value format

src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py
Fixes
- Add field aliases to PricingFilter model to match AWS API requirements (Field, Type, Value)
- Configure Pydantic to validate by alias for proper API serialization
__Before:__ AWS Price List API calls with filters failed due to incorrect field casing (field, type, value) 
__After:__ Filters work correctly with proper capitalized field names as required by AWS API
Is this a breaking change? No
Checklist:
=> fix: cost-analysis-mcp-server: Fix AWS Price List API filter field capitalization

README.md, src/documentdb-mcp-server/README.md
- Add config for Q Developer CLI
- Add arguments trouble shooting for Q Developer CLI
Fixes
- Add DocumentDB MCP client config at README.md because there's no MCP client (e.g. Q Developer CLI) config
- Add arguments trouble shooting for Q Developer CLI
- I can't find the any guide about client config, so I thought it was not possible to use the DocumentDB MCP in the Q Developer CLI. Additionally, I wasted a lot of time trying to connect the MCP to the Q Developer CLI.
- Through changes to the relevant documentation, users can now easily set up the MCP for document db.
- Add a guide to help users manually run the MCP if it is not executing or if the MCP is …
=> docs: add DocDB mcp client config for Q Developer CLI & troubleshoot guide for MCP client

src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/server_aws.py, src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/server_aws_cn.py, src/aws-documentation-mcp-server/awslabs/aws_documentation_mcp_server/server_utils.py, src/aws-documentation-mcp-server/tests/test_server_aws.py, src/aws-documentation-mcp-server/tests/test_server_aws_cn.py, src/aws-documentation-mcp-server/tests/test_server_utils.py, src/aws-documentation-mcp-server/uv.lock
Fixes
Updating the tools in this MCP server to include a Query Parameter with the session UUID for tracking purposes. Last week a similiar PR was created that used authorization headers, but the logging team has rediscovered that they cannot track custom headers in their logging system for GET requests so we're shifting back to the query param approach.
The URLs that users use to GET and POST to using this tool will now have a query param. No functional changes will result from this changed.
Checklist: …
=> feat: Session id with query param

README.md, src/iam-mcp-server/README.md, src/iam-mcp-server/awslabs/iam_mcp_server/models.py, src/iam-mcp-server/awslabs/iam_mcp_server/server.py, src/iam-mcp-server/tests/test_errors.py, src/iam-mcp-server/tests/test_server.py, src/iam-mcp-server/uv.lock
This feature adds comprehensive IAM group management capabilities to the AWS IAM MCP Server, enabling AI assistants to create, manage, and organize IAM groups
alongside users and roles. The feature includes:
- Core Group Operations: Create, list, retrieve, and delete IAM groups with optional force cleanup
- Group Membership Management: Add and remove users from groups to organize permissions at scale
- Group Policy Management: Attach and detach managed policies to/from groups for centralized permission control
- Advanced Filtering: List groups with path prefix filtering for organizational structure navigation
- Security Integration: Full read-only mode support and comprehensive error handling
- Best Practices Compliance: Follows AWS IAM security patterns with proper validation and cleanup …
=> feat(iam-mcp-server): add group management operations

README.md, docs/index.md, src/cost-analysis-mcp-server/README.md, src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py
Fixes
This change adds deprecation warnings throughout the cost-analysis-mcp-server to guide users toward the AWS Pricing MCP Server.
**Before**: Users could discover and use the cost-analysis-mcp-server without any indication that it's deprecated or that there's a preferred alternative.
**After**: Users will see clear deprecation warnings at multiple touchpoints: server listings, server docs, MCP server and tool descriptions.
This provides a clear migration path and prevents new users from adopting deprecated functionality.
**RFC issue number**: #562 
Checklist:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …
=> docs(cost-analysis-mcp-server): Add deprecation warning

.github/CODEOWNERS, src/aws-dataprocessing-mcp-server/README.md
Fixes
Add Service owners for Data Processing MCP server
1. Made changes in .github/codeowners to add more dataprocessing mcp owners
> Before
Dataprocessing Code Owners needs to take approvals from away team, which added a lot of turnaround time
> After
Dataprocessing Code Owners would be able to accelerate pushes
Checklist:
=> chore(dataprocessing-mcp-server): Add Service owners for Data Processing MCP server

src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/core/glue_data_catalog/data_catalog_database_manager.py, src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/core/glue_data_catalog/data_catalog_handler.py, src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/core/glue_data_catalog/data_catalog_table_manager.py, src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/handlers/glue/data_catalog_handler.py, src/aws-dataprocessing-mcp-server/awslabs/aws_dataprocessing_mcp_server/models/data_catalog_models.py, src/aws-dataprocessing-mcp-server/tests/core/glue_data_catalog/test_data_catalog_handler.py, src/aws-dataprocessing-mcp-server/tests/core/glue_data_catalog/test_data_catalog_table_manager.py, src/aws-dataprocessing-mcp-server/tests/handlers/glue/test_data_catalog_handler.py, src/aws-dataprocessing-mcp-server/uv.lock
- Fixed MCP managed tagging issue in AWS Glue Data Catalog MCP tools
- Remove incorrect param in `create-table` call
- Enable hide-password by default for get/list connections operations
- `Create-table` fail due to unable to append mcp managed tag
- Password is displayed from Glue get/list connection reponse
- `create-table` is able to create resource and append the correct tag
- connection password is hidden from AWS Glue API response
N
Checklist:
=> fix(aws-dataprocessing-mcp-server): Fixed MCP managed tagging issue in AWS Glue Data Catalog MCP tools

src/cost-analysis-mcp-server/awslabs/cost_analysis_mcp_server/server.py, src/cost-analysis-mcp-server/tests/test_server.py
Fixes
Follow-up to #772.
Add deprecation warnings for the `cost-analysis-mcp-server`, indicating it should no longer be used in favor of the AWS Pricing MCP Server.
See #772 
Is this a breaking change? Y
**RFC issue number**: #562 
Checklist:
=> docs(cost-analysis-mcp-server): Add deprecation warnings (part 2)

src/aws-dataprocessing-mcp-server/README.md
Fixes
1. Update READMe for dataprocessing mcp server to reduce mcp server name.
2. Add a fix on the pypi library
Changes made in the readme file to provide more ease of use for customers who are using aws-dataprocessing-mcp-server
> before
Users may need to update the mcp server name to reduce the tool name length
> after
with the reduction of the mcp server name, most tools would be compatible with 60 length limit
https://github.com/awslabs/mcp/issues/614
Checklist:
=> chore(aws-dataprocessing-mcp-server): Update MCP server name and pypi library in readme

.github/CODEOWNERS, src/s3-tables-mcp-server/CONTEXT.md, src/s3-tables-mcp-server/README.md
Add CONTEXT.md file to improve Amazon Q experience
- Add codeowners for S3 Tables MCP
- Update README.md with a description of how to use CONTEXT.md
- Add CONTEXT.md for Amazon Q
Since, S3 Tables is relatively new technology, LLMs don't have much context about it and Amazon Q tries to use AWS CLI for S3 Tables operations.
After adding CONTEXT.md to contexts of Amazon Q, LLM will use MCPs with higher probability.
Without context:
```
> list all tables
> I'll help you list the tables, but I need to know which database system you're using and where to look for these tables. Are you looking for:
1. AWS DynamoDB tables?
2. Tables in a specific database (MySQL, PostgreSQL, etc.)?
3. Tables in a specific file or directory?
Could you provide more details about what tables you're trying to list …
```
=> feat: add CONTEXT.md, update CODEOWNERS and README

src/aws-pricing-mcp-server/README.md
Fixes
* Add Windows installation instructions
* 
Before, Windows users got errors when they used the (Mac/Linux) installation instructions.
After, they can copy the Windows-specific configuration.
Checklist:
=> docs(aws-pricing-mcp-server): Add Windows installation instructions

src/aws-api-mcp-server/pyproject.toml, src/aws-api-mcp-server/uv.lock
Reverting package version to 0.1.1 since 0.1.2 has not yet been released to PyPi.
Checklist:
=> chore(aws-api-mcp-server): change version back to 0.1.1

src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/service.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/server.py, src/aws-api-mcp-server/tests/aws/test_service.py, src/aws-api-mcp-server/tests/test_server.py
The profile wasn't working for customizations because it was solely used for the interpretation of service-based operations into boto3 API calls. This prevented customizations like `s3 ls` to work for instance when only SSO-based credentials via profiles were used.
Fixes https://github.com/awslabs/mcp/issues/892
This PR injects `AWS_API_MCP_PROFILE_NAME` when it is provided for AWS CLI customizations. AWS CLI customizations are not interpreted via the `boto3` interpretation pipeline because these are Python classes with deterministic API calls.  
* Before
* After
By submitting this pull request, I confirm that you …
=> chore(aws-api-mcp-server): support profile for customizations

.github/actions/build-and-push-container-image/action.yml, .github/workflows/release-merge-tag.yml
* Merge automation failing due to checking remote too fast
* Saving image is not finding expected target.
* Add a sleep
* Add debugging and failure prevention (will be removed after fixes)
Checklist:
=> fix: avoid checking remote too fast and image save debugging

src/aws-api-mcp-server/CHANGELOG.md, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/__init__.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/driver.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/service.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/common/command.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/parser/parser.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/server.py, src/aws-api-mcp-server/tests/aws/test_driver.py, src/aws-api-mcp-server/tests/aws/test_service.py, src/aws-api-mcp-server/tests/fixtures.py, src/aws-api-mcp-server/tests/parser/test_parser.py, src/aws-api-mcp-server/tests/test_server.py, src/aws-api-mcp-server/uv.lock
Fixes
Add support for `--profile` to boto operations. The `--profile` flag was just ignored before but we are already supporting thus for the cli customizations. This allows users to make requests like `List the s3 buckets for profile X`. This will take precedence over `AWS_API_MCP_PROFILE_NAME`.
Users can request to run operations for certain profiles.
Checklist: …
=> fix(aws-api-mcp-server): Add profile support to boto3 operations

.github/CODEOWNERS
Add additional maintainer to the HealthOmics MCP server codeowners
Adds @WIIASD as a code owner for AWS HealthOmics MCP server
added github ID to `.github/CODEOWNERS`
N/A
N
Checklist:
=> feat: add @WIIASD as codeowner for aws-healthomics-mcp-server

src/aws-knowledge-mcp-server/README.md
We need the python package https://pypi.org/project/mcp-proxy/,  not the other tool that aggregates and serves multiple MCP resource servers through a single HTTP server.
=> docs: mcp-proxy links to wrong project

src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/dense_retriever.py
When installing server using uvx on Mac, suggest_aws_command returns irrelevant results. This happens because CPU device is used on Ubuntu runner that generates embeddings, while MPS (Metal Performance Shaders) is preferred on OSX, when encoding query.
Pins device to CPU when initializing SentenceTransformer.
Should fix irrelevant results being returned on OSX.
Checklist:
=> fix: Pin CPU device in SentenceTransformer

src/ccapi-mcp-server/README.md, src/ccapi-mcp-server/awslabs/ccapi_mcp_server/server.py
The CC API MCP server was previously providing recomendations to the LLM and in the documentation for the MCP to _not_ use tools like use_aws and the AWS API MCP
This is not the desired posture of the CC API MCP. The CC API MCP gives additional deterministic proactive security controls like checkov and hooks to users to enforce what kind of changes go into you account. It is up to the user to decide which set of tools it wants to enable and the decision to disable any other MCP should not be a part of our MCP's prompt
Removed references to tool restriction from the MCP instructions as well as the readme
If the user has the AWS API MCP or is using Q with use_aws enabled, now the LLM is more likely to choose those tools. An acknowledged side-effect of this change is that if a user has both …
=> fix(ccapi-mcp): Removing all tool selection restriction wording from CC API MCP

src/ccapi-mcp-server/awslabs/ccapi_mcp_server/server.py
Fixes #1147 
This PR fixes a UnicodeEncodeError that causes ccapi-mcp-server to crash on Windows when using the `--readonly` flag. The issue occurs because Windows console uses cp1252 encoding which cannot handle Unicode emoji characters.
Replaced Unicode emoji characters (⚠️) with ASCII text equivalent in the read-only mode warning message. Changed `⚠️ READ-ONLY MODE ACTIVE ⚠️` to `[WARNING] READ-ONLY MODE ACTIVE [WARNING]` to prevent UnicodeEncodeError on Windows systems using cp1252 encoding.
**Before**: ccapi-mcp-server crashes immediately on Windows when started with `--readonly` flag, preventing any MCP functionality from working.
**After**: Server starts successfully on Windows with `--readonly` flag and displays a clear ASCII warning message, allowing users to use the server in …
=> fix: resolve windows cp1252 encoding issue

src/redshift-mcp-server/awslabs/redshift_mcp_server/consts.py, src/redshift-mcp-server/awslabs/redshift_mcp_server/redshift.py, src/redshift-mcp-server/tests/test_server.py
Implements https://github.com/awslabs/mcp/issues/1180.
Implementing the request to be able to track the MCP issued activity in the Redshift logs.
- Added application_name setting to identify MCP server queries
- Updated query execution to handle additional SET statement
- Fixed tests for adding application_name statement
- (little extra) Refactored client timeout constants for clarity
Users will be able to track the MCP sessions via the application_name column in stl_connection_log and sys_connection_log system tables in Redshift clusters.
* [N/A] Changes are documented
**RFC issue number**: 1180
Checklist:
* [N/A] Migration process documented
* [N/A] Implement warnings (if it can live side …
=> feat(redshift-mcp-server): set application name, minor config updates

.github/workflows/release.yml
Allows docker build due to <19Gb disk space for the core.
Checklist:
=> fix: core release requires disk space

src/aws-api-mcp-server/CHANGELOG.md, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/service.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/aws/services.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/kb/dense_retriever.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/parser/parser.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/core/security/policy.py, src/aws-api-mcp-server/awslabs/aws_api_mcp_server/server.py, src/aws-api-mcp-server/pyproject.toml, src/aws-api-mcp-server/tests/test_security_policy.py
Fixes
- `READ_OPERATIONS_ONLY_MODE` and `REQUIRE_MUTATION_CONSENT` was not checked in the security policy causing the wrong decision being returned. This PR implements a quick fix but I think we need some refactoring in the `call_aws` function.
- Add linter rule to catch unused function arguments
- Switching to `0.3.0` version with this bug fix
Checklist: …
=> fix(aws-api-mcp-server): check read only and consent env vars in security policy

src/cloudwatch-appsignals-mcp-server/awslabs/cloudwatch_appsignals_mcp_server/trace_tools.py, src/cloudwatch-appsignals-mcp-server/tests/test_server.py
Fixes
Log group will not properly default to `aws/spans` log group due to this [if condition](https://github.com/awslabs/mcp/blob/b8a10f85bb4a021292e715b90a796a3456281b94/src/cloudwatch-appsignals-mcp-server/awslabs/cloudwatch_appsignals_mcp_server/trace_tools.py#L194) and this [default parameter value](https://github.com/awslabs/mcp/blob/b8a10f85bb4a021292e715b90a796a3456281b94/src/cloudwatch-appsignals-mcp-server/awslabs/cloudwatch_appsignals_mcp_server/trace_tools.py#L120). Empty strings are not considered `None` in Python.
> Change if condition in `search_transaction_spans` tool …
=> fix: default log group in search_transaction_spans tool for empty string

src/aws-dataprocessing-mcp-server/README.md
Fix missing comma that results in malformed IAM Policy JSON
Fixes
Add missing comma to IAM policy in docs 
> Update data processing MCP server README.md to fix a malformed IAM Policy for read operations at https://awslabs.github.io/mcp/servers/aws-dataprocessing-mcp-server#read-only-operations-policy
* [ x] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [ x] I have performed a self-review of this change
* [ x] Changes have been tested
* [ x] Changes are documented
N
Checklist:
Migration or implement warnings not required
By …
=> fix(doc): fix IAM policy definition in README

docusaurus/package-lock.json, docusaurus/package.json
After upgrade the GitHub Pages show 404 so backing out change.
Checklist:
=> fix: backout docusaurus update

.github/CODEOWNERS
Alphabetizing all the packages 
All packages will have the maintainers and the admins plus individual contributors.
Checklist:
=> fix: add maintainers to all src
